config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show]
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image, dependent: false
  has_one_attached :image
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  attr_accessor :remove_image
  validates :content, length: { maximum: 2000 }, presence: true
  before_save :remove_image_if_user_accept

  private

  def remove_image_if_user_accept
    self.image = nil if ActiveRecord::Type::Boolean.new.cast(remove_image)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = Comment.new(comment_params)
        @comment.user_id = current_user.id
        if @comment.save
            redirect_back(fallback_location: root_path)
        else
            redirect_back(fallback_location: root_path)
        end
    
    end
    
    
        private
        
        def comment_params
        params.require(:comment).permit(:content,:post_id)
        end
    end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like = current_user.likes.create(post_id: params[:post_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        @like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.page(params[:page]).per(7)
    @users = User.all
    @like = Like.new
    
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "投稿完了" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "投稿更新" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "投稿削除" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(
        :image, :remove_image, :content
      )
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CotactApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar  bg-secondary">
              <%=link_to"Contact App",posts_path,class: "navbar-brand text-white"%>
      <div class="d-flex flex-nowrap ">
              <%= link_to "投稿する", new_post_path, class: "nav-link text-white text-center"%><i class="fas fa-book-open text-white d-flex align-items-center mr-5"></i>
              <%= link_to "マイページへ", user_path(current_user.id) , class: "nav-link text-white "%>
              <%= link_to "ユーザー一覧へ", users_path, class: "nav-link text-white text-center" %>
              <%= link_to "ログアウト", destroy_user_session_path, :method => :delete, class: "nav-link text-white " %>
        </ul>
      </div>
    </nav>
  <%end%>
        <% if flash[:notice] %>
          <div class="alert alert-success" role="alert">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%if flash[:alert]%>
          <div class="alert alert-danger" role="alert">
            <%= flash[:alert]%>
          </div>
        <% end %>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "つのエラーです。空文字はやめてください") %> </h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="card col-12">
      <div class="field text-center">
        <%= form.label :content, class: "from-control col-10"%>
        <%= form.text_field :content , class: "from-control col-8"%>
      </div>
      <div class = "field col-12 text-center">
        <%= form.label :image ,class:"col-12"%>
        <%= form.file_field :image, class: "form-control-file col-12 "%> 
      </div>

    <div class = "field  d-flex justify-content-center  flex-wrap mt-3">  
        <%= form.submit "投稿", class: "btn btn-primary col-7 "%>
    </div>
      <div class = "form-group">
        <% if @post.image.attached? && @post.image.blob&.persisted?%>
          <div class = "heckbox">
            <label>
              <%= form.check_box :remove_image%>
              画像を削除する
            </label>
          </div>
        <%end%>
      </div>
<% end %>

app/views/posts/edit.html.erb
<div class = "field  d-flex justify-content-center col-12 flex-wrap mt-5">  
<h1>編集</h1>
</div>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<div class ="d-flex justify-content-center col-12 flex-wrap">
    <% @posts.each do |post| %>
        <div class  = "bg-light  border border-dark rounded-pill col-6 d-flex flex-nowrap mb-3">
            <p class = "mt-3"><a href="/posts/<%= post.id %>"><%= post.content %></a> 
            <%if post.liked_users.count != 0%> 👍<%= post.liked_users.count %></p>
            <%end%>
        </div>
            <h5>作成者</h5><a href="/users/<%= post.user.id %>">(
                    <%if !post.user.nickname.presence%>
                        匿名)
                    <%else%>
                        <%= post.user.nickname %>)</a>
                    <% end %>
    <%end%>
    
</div>
<div class = "d-flex justify-content-center flex-wrap col-12 mb-5 mt-2">
    <%= paginate @posts%>
</div>

app/views/posts/new.html.erb
<div class = "field  d-flex justify-content-center  flex-wrap mt-5">  
  <h2 class = "col-12">投稿</h2>


  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
    <h1>投稿詳細ページ</h1>
<div class = "field  d-flex justify-content-center col-12 flex-wrap mt-5 text-center">
  <div class ="card col-6">  
        <%if !@post.user.nickname.presence%>
          <h3>匿名さんの投稿</h3>
          <h3>「<%= @post.content %>」</h3>
        <%else%>
          <h3><a href="/users/<%= @post.user.id %>"><%= @post.user.nickname %></a></h3>
          <h3><%= @post.content %></h3>
        <%end%>
    <div class = "row">
        <div class = "col-12">
            <div  class = "card mb-2">
              <%if @post.image.attached?%>
                <%= image_tag @post.image, class: "card-img-top"%>
              <%end%>
            </div>
        </div>
    </div>
      <h3>いいねの数 <%= @post.likes.count %></h3>
        <% if current_user.already_liked?(@post) %>
          <%= button_to 'いいねを取り消す', post_like_path(@post),class: "btn btn-outline-info", method: :delete %>
        <% else %>
          <%= button_to 'いいね', post_likes_path(@post),class: "btn btn-outline-info" %>
        <% end %>
        <h2>いいねしたユーザー</h2>
        <% @post.liked_users.each do |user| %>
          <%if !user.nickname.presence%>
            <a>匿名さん</a>
          <%else%>
            <%= user.nickname %>
          <% end %>
        <%end%>

    <h2 class ="card-text mt-5">コメント覧</h2>
    <% @comments.each do |c| %>
      <div>
        <%if !@post.user.nickname.presence%>
          <a>匿名</a>
          <a>「<%= c.content %>」</a>
        <%else%>
          <a href="/users/<%= @post.user.id %>"><%= @post.user.nickname %></a>
          <a>「<%= c.content %>」</a>
        <%end%>
        <hr>
      </div>
    <% end %>

    <%= form_for [@post, @comment] do |f| %>
      <%= f.text_field :content %>
        <%= f.hidden_field :post_id, value: @post.id %>
      <br>
      <%= f.submit 'コメントする', class: "btn btn-primary col-3  mt-4" %>
    <% end %>

    <%= link_to "ホームへ戻る", posts_path %>
  </div>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
  <a href="/users/<%= user.id %>"><%= user.nickname %></a>
  <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>

app/views/users/show.html.erb
<h1>ユーザー詳細ページ</h1>
<div class = "field  d-flex justify-content-center col-12 flex-wrap mt-5">
  <div class ="card col-6 text-center">
    <%if !@user.nickname.presence%>
    <h3>匿名さん</h3>
    <%else%>
    <h3><%= @user.nickname %></h3>
    <%end%>
    <h2>投稿した内容</h2>
    <% @user.posts.each do |post| %>
      <p href="/posts/<%= post.id %>"><%= post.content %></p>
      <p><%= link_to '編集', edit_post_path(post) %></p>
      <hr>
    <% end %>
    <h3>いいねしている投稿</h3>
        <% @user.liked_posts.each do |post| %>
          <ul>
              <%if !post.user.nickname.presence%>
                <a>匿名さん</a>
                「<%= post.content %>」
              <%else%>
                <%= post.user.nickname %>さん
                「<%= post.content %>」
              <%end%>
        </ul>
        <% end %>
  </div>
</div>